module.exports = {
  roots: ['<rootDir>/'],
  preset: 'ts-jest',
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testRegex: '.spec.[jt]s$',
  modulePathIgnorePatterns: ['/infra/'],
  moduleFileExtensions: ['js', 'jsx', 'ts', 'tsx', 'json', 'node'],
  testEnvironment: 'node',
  coverageProvider: 'v8',
  collectCoverage: false,
  coverageDirectory: '<rootDir>/coverage/',
  coverageReporters: ['lcov', 'text', 'cobertura', 'html'],
  testPathIgnorePatterns: ['dist'],
  collectCoverageFrom: [
    'src/**/*.{js,ts,jsx,tsx}',
    './*.{js,ts,jsx,tsx}',
    '!.eslint*.js',
    '!babel.*.js',
    '!commitlint.*.js',
    '!jest.*.js',
    '!lint-staged.*.js',
    '!prettier.*.js',
    '!release.*.js',
    '!**/*.d.{ts,tsx}',
    '!**/node_modules/**',
    '!webpack.config.js',
    '!src/test/**',
  ],
}
